import React, { createContext, useContext, useState, useCallback } from 'react';

export type Language = 'en' | 'vi';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.portfolio': 'Portfolio',
    'nav.cv_builder': 'CV Builder',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    // Landing
    'landing.hero.title': 'Design fast, beautiful, high-performance websites',
    'landing.hero.subtitle': 'I build you a professional website that loads fast, is easy to use, budget-friendly, and ready to scale later.',
    'landing.hero.cta1': 'View projects',
    'landing.hero.cta2': 'Contact now',
    'landing.hero.cta2.note': 'Zalo: 0395659769',
    'landing.value.title': 'Why work with me',
    'landing.value.item1.title': 'User-first, not just pretty',
    'landing.value.item1.desc': 'Every decision focuses on clarity, conversion, and ease of use.',
    'landing.value.item2.title': 'Real speed optimization',
    'landing.value.item2.desc': 'Measure and improve Core Web Vitals, not only a flashy demo.',
    'landing.value.item3.title': 'Clean, upgradeable code',
    'landing.value.item3.desc': 'Structured, documented, and ready for future features.',
    'landing.value.item4.title': 'Transparent pricing',
    'landing.value.item4.desc': 'Clear scope, no hidden fees, updates along the way.',
    'landing.value.item5.title': 'Post-launch support',
    'landing.value.item5.desc': 'I stay to monitor, fix, and improve after hand-off.',
    'landing.services.title': 'Services',
    'landing.services.landing.title': 'Landing Page',
    'landing.services.landing.desc': 'Concise, beautiful, conversion-focused. Perfect for ads.',
    'landing.services.business.title': 'Business website',
    'landing.services.business.desc': 'Service & brand introduction. SEO-ready, easy to manage.',
    'landing.services.advanced.title': 'Advanced site',
    'landing.services.advanced.desc': 'Admin, dashboard, API. Performance and security tuned.',
    'landing.portfolio.title': 'Selected projects',
    'landing.portfolio.pattern': 'Website for {audience}',
    'landing.portfolio.problem': 'Problem',
    'landing.portfolio.solution': 'Solution',
    'landing.portfolio.result': 'Result',
    'landing.process.title': 'How we work',
    'landing.process.step1': 'Step 1: Discuss needs → consult',
    'landing.process.step2': 'Step 2: Clear quotation',
    'landing.process.step3': 'Step 3: Build demo → refine',
    'landing.process.step4': 'Step 4: Complete → handover',
    'landing.process.step5': 'Step 5: Ongoing support',
    'landing.pricing.title': 'Pricing snapshot',
    'landing.pricing.mini.title': 'Mini',
    'landing.pricing.mini.desc': 'Landing page for campaigns',
    'landing.pricing.basic.title': 'Basic',
    'landing.pricing.basic.desc': 'Company intro site',
    'landing.pricing.advanced.title': 'Advanced',
    'landing.pricing.advanced.desc': 'Professional site with custom flows',
    'landing.pricing.note': 'Domain & hosting not included. I help optimize cost.',
    'landing.commitments.title': 'Commitments',
    'landing.commitments.item1': 'Do it right, not rushed.',
    'landing.commitments.item2': 'Speed + UX optimized.',
    'landing.commitments.item3': 'No hidden fees.',
    'landing.commitments.item4': 'Support after handover.',
    'landing.testimonials.title': 'Client reactions (directional)',
    'landing.testimonials.quote1': '“Site loads faster, customers find it easier.”',
    'landing.testimonials.quote2': '“Fair price, but very thorough work.”',
    'landing.testimonials.quote3': '“Responsive support, easy to collaborate.”',
    'landing.cta.final.title': 'Need a website but not sure where to start?',
    'landing.cta.final.subtitle': 'I will help you pick the best solution for your budget.',
    'landing.cta.final.primary': 'Talk on Zalo',
    'landing.cta.final.secondary': 'See portfolio',
    // Portfolio
    'portfolio.hero.greeting': 'Trusted by Enterprise & Startup Teams',
    'portfolio.hero.name': 'Nguyen Thai Binh Duong',
    'portfolio.hero.title': 'Award-Caliber Frontend Developer | High-Performance Solutions',
    'portfolio.hero.subtitle': 'I don\'t just build interfaces—I engineer scalable, pixel-perfect digital experiences that drive measurable business results. 1.5 years of verifiable excellence with 10K+ monthly active users.',
    'portfolio.hero.cta': 'View My Work',
    'portfolio.hero.contact': 'Get in Touch',
    'portfolio.about.title': 'Why Clients Trust Me',
    'portfolio.about.text': 'Proven Track Record: Successfully delivered 5+ production applications serving 10K+ monthly active users with zero downtime. Built dashboards handling 100K+ medical records with HIPAA compliance. Optimized booking flows by 50%. | 💎 Enterprise-Grade Quality: Architected Design Systems reducing development time by 45%, implemented 60fps real-time features, and consistently deliver pixel-perfect implementations exceeding specifications. | 🎯 Results-Driven Partnership: I engineer sustainable solutions that scale. Your project becomes my priority, and reliability is non-negotiable. Every feature is optimized for performance, accessibility, and user delight.',
    'portfolio.skills.title': 'Technical Expertise & Proficiency',
    'portfolio.projects.title': 'Proven Success Stories',
    'portfolio.experience.title': 'Professional Track Record',
    'portfolio.services.title': 'What I Deliver',
    'portfolio.testimonials.title': 'Client Success & Trust',
    'portfolio.contact.title': 'Ready to Transform Your Vision?',
    'portfolio.contact.subtitle': 'Let\'s build something remarkable together. With my proven expertise in high-performance web development, your project will exceed expectations.',
    'portfolio.contact.name': 'Your Name',
    'portfolio.contact.email': 'Your Email',
    'portfolio.contact.message': 'Your Message',
    'portfolio.contact.send': 'Send Message',
    // CV Builder
    'cv.title': 'CV Builder',
    'cv.subtitle': 'Create a professional resume tailored for IT roles',
    'cv.editor': 'Editor',
    'cv.preview': 'Preview',
    'cv.export': 'Export PDF',
    'cv.template': 'Template',
    'cv.personal': 'Personal Info',
    'cv.summary': 'Professional Summary',
    'cv.skills': 'Skills',
    'cv.experience': 'Work Experience',
    'cv.education': 'Education',
    'cv.projects': 'Projects',
    'cv.certifications': 'Certifications',
    'cv.languages': 'Languages',
    'cv.fullname': 'Full Name',
    'cv.jobtitle': 'Job Title',
    'cv.phone': 'Phone',
    'cv.location': 'Location',
    'cv.website': 'Website',
    'cv.company': 'Company',
    'cv.role': 'Role',
    'cv.duration': 'Duration',
    'cv.description': 'Description',
    'cv.add': 'Add',
    'cv.remove': 'Remove',
    'cv.school': 'School',
    'cv.degree': 'Degree',
    'cv.project_name': 'Project Name',
    'cv.tech_stack': 'Tech Stack',
    // Common
    'common.dark_mode': 'Dark Mode',
    'common.light_mode': 'Light Mode',
    'common.language': 'Language',
    'common.download_cv': 'Download CV',
  },
  vi: {
    'nav.home': 'Trang chủ',
    'nav.portfolio': 'Portfolio',
    'nav.cv_builder': 'Tạo CV',
    'nav.about': 'Giới thiệu',
    'nav.contact': 'Liên hệ',
    'landing.hero.title': 'Thiết kế website nhanh – đẹp – tối ưu hiệu năng',
    'landing.hero.subtitle': 'Tôi giúp bạn có website chuyên nghiệp, tải nhanh, dễ dùng, hợp ngân sách và dễ mở rộng về sau.',
    'landing.hero.cta1': 'Xem dự án',
    'landing.hero.cta2': 'Liên hệ ngay',
    'landing.hero.cta2.note': 'Zalo: 0395659769',
    'landing.value.title': 'Giá trị khác biệt',
    'landing.value.item1.title': 'Không làm web “cho có”',
    'landing.value.item1.desc': 'Tập trung trải nghiệm, rõ ràng, chuyển đổi tốt.',
    'landing.value.item2.title': 'Tối ưu tốc độ thật',
    'landing.value.item2.desc': 'Đo lường Core Web Vitals, không chỉ demo đẹp.',
    'landing.value.item3.title': 'Code rõ ràng, dễ nâng cấp',
    'landing.value.item3.desc': 'Cấu trúc chuẩn, có ghi chú, sẵn sàng mở rộng.',
    'landing.value.item4.title': 'Giá minh bạch từ đầu',
    'landing.value.item4.desc': 'Phạm vi rõ, không phí ẩn, báo tiến độ thường xuyên.',
    'landing.value.item5.title': 'Support sau bàn giao',
    'landing.value.item5.desc': 'Theo dõi, sửa lỗi, tối ưu thêm sau khi bàn giao.',
    'landing.services.title': 'Dịch vụ',
    'landing.services.landing.title': 'Landing Page',
    'landing.services.landing.desc': 'Gọn, đẹp, tối ưu chuyển đổi. Phù hợp chạy quảng cáo.',
    'landing.services.business.title': 'Website doanh nghiệp',
    'landing.services.business.desc': 'Giới thiệu dịch vụ, thương hiệu. Chuẩn SEO, dễ quản lý.',
    'landing.services.advanced.title': 'Website nâng cao',
    'landing.services.advanced.desc': 'Có admin, dashboard, API. Tối ưu hiệu năng, bảo mật.',
    'landing.portfolio.title': 'Dự án gần đây',
    'landing.portfolio.pattern': 'Website cho {audience}',
    'landing.portfolio.problem': 'Vấn đề',
    'landing.portfolio.solution': 'Giải pháp',
    'landing.portfolio.result': 'Kết quả',
    'landing.process.title': 'Quy trình làm việc',
    'landing.process.step1': 'B1: Trao đổi & Tư vấn',
    'landing.process.step2': 'B2: Báo giá rõ ràng',
    'landing.process.step3': 'B3: Làm demo & chỉnh sửa',
    'landing.process.step4': 'B4: Hoàn thiện &bàn giao',
    'landing.process.step5': 'B5: Hỗ trợ sau triển khai',
    'landing.pricing.title': 'Bảng giá rút gọn',
    'landing.pricing.mini.title': 'Mini',
    'landing.pricing.mini.desc': 'Landing page chiến dịch',
    'landing.pricing.basic.title': 'Cơ bản',
    'landing.pricing.basic.desc': 'Web giới thiệu doanh nghiệp',
    'landing.pricing.advanced.title': 'Nâng cao',
    'landing.pricing.advanced.desc': 'Web chuyên nghiệp, luồng riêng',
    'landing.pricing.note': 'Không gồm domain + hosting. Có tư vấn tối ưu chi phí.',
    'landing.commitments.title': 'Cam kết',
    'landing.commitments.item1': 'Làm kỹ, không làm cho xong.',
    'landing.commitments.item2': 'Tối ưu tốc độ + UX.',
    'landing.commitments.item3': 'Không phát sinh phí mập mờ.',
    'landing.commitments.item4': 'Hỗ trợ sau bàn giao.',
    'landing.testimonials.title': 'Phản hồi định hướng',
    'landing.testimonials.quote1': '“Web chạy nhanh hơn, khách dễ dùng hơn.”',
    'landing.testimonials.quote2': '“Giá hợp lý nhưng làm rất kỹ.”',
    'landing.testimonials.quote3': '“Support nhanh, dễ làm việc.”',
    'landing.cta.final.title': 'Bạn cần website nhưng chưa biết bắt đầu từ đâu?',
    'landing.cta.final.subtitle': 'Tôi sẽ giúp bạn chọn giải pháp phù hợp nhất với ngân sách.',
    'landing.cta.final.primary': 'Nhắn Zalo ngay',
    'landing.cta.final.secondary': 'Xem portfolio',
    'portfolio.hero.greeting': 'Được Tin Tưởng Bởi Doanh Nghiệp & Startup',
    'portfolio.hero.name': 'Nguyễn Thái Bình Dương',
    'portfolio.hero.title': 'Frontend Developer Chuyên Nghiệp | Giải Pháp Hiệu Năng Cao',
    'portfolio.hero.subtitle': 'Tôi không chỉ xây dựng giao diện—tôi thiết kế những trải nghiệm số có khả năng mở rộng, đạt chuẩn pixel-perfect, mang lại kết quả kinh doanh đo lường được. 1.5 năm thành công được chứng minh với 10K+ người dùng hoạt động hàng tháng.',
    'portfolio.hero.cta': 'Xem Dự Án',
    'portfolio.hero.contact': 'Liên Hệ',
    'portfolio.about.title': 'Tại Sao Khách Hàng Tin Tưởng Tôi',
    'portfolio.about.text': '✅ Lịch Sử Thành Công: Bàn giao 5+ ứng dụng production với 10K+ user/tháng, 0 downtime. Dashboard xử lý 100K+ bản ghi đạt HIPAA. Tối ưu booking giảm 50%. | 💎 Chất Lượng Enterprise: Design System giảm 45% dev time, real-time 60fps, pixel-perfect mỗi lần. | 🎯 Đối Tác Định Hướng Kết Quả: Thiết kế giải pháp bền vững & mở rộng. Dự án của bạn là ưu tiên hàng đầu. Mỗi tính năng tối ưu hệ thống, tiếp cận & UX.',
    'portfolio.skills.title': 'Chuyên Môn & Trình Độ Kỹ Năng',
    'portfolio.projects.title': 'Những Câu Chuyện Thành Công',
    'portfolio.experience.title': 'Lịch Sử Hành Động Chuyên Nghiệp',
    'portfolio.services.title': 'Tôi Cung Cấp Gì',
    'portfolio.testimonials.title': 'Sự Tin Tưởng & Thành Công Khách Hàng',
    'portfolio.contact.title': 'Sẵn Sàng Biến Tầm Nhìn Thành Hiện Thực?',
    'portfolio.contact.subtitle': 'Cùng xây dựng sản phẩm ấn tượng. Với chuyên môn web hiệu năng cao được chứng minh, dự án của bạn sẽ vượt qua mọi kỳ vọng.',
    'portfolio.contact.name': 'Họ và tên',
    'portfolio.contact.email': 'Email',
    'portfolio.contact.message': 'Tin nhắn',
    'portfolio.contact.send': 'Gửi Tin Nhắn',
    'cv.title': 'Tạo CV',
    'cv.subtitle': 'Tạo CV chuyên nghiệp dành cho ngành IT',
    'cv.editor': 'Chỉnh sửa',
    'cv.preview': 'Xem trước',
    'cv.export': 'Xuất PDF',
    'cv.template': 'Mẫu',
    'cv.personal': 'Thông tin cá nhân',
    'cv.summary': 'Giới thiệu chuyên môn',
    'cv.skills': 'Kỹ năng',
    'cv.experience': 'Kinh nghiệm làm việc',
    'cv.education': 'Học vấn',
    'cv.projects': 'Dự án',
    'cv.certifications': 'Chứng chỉ',
    'cv.languages': 'Ngôn ngữ',
    'cv.fullname': 'Họ và tên',
    'cv.jobtitle': 'Chức danh',
    'cv.phone': 'Số điện thoại',
    'cv.location': 'Địa chỉ',
    'cv.website': 'Website',
    'cv.company': 'Công ty',
    'cv.role': 'Vị trí',
    'cv.duration': 'Thời gian',
    'cv.description': 'Mô tả',
    'cv.add': 'Thêm',
    'cv.remove': 'Xoá',
    'cv.school': 'Trường',
    'cv.degree': 'Bằng cấp',
    'cv.project_name': 'Tên dự án',
    'cv.tech_stack': 'Công nghệ',
    'common.dark_mode': 'Chế độ tối',
    'common.light_mode': 'Chế độ sáng',
    'common.language': 'Ngôn ngữ',
    'common.download_cv': 'Tải CV',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>('en');

  const t = useCallback((key: string): string => {
    return translations[lang][key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
