name: CI/CD Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # chỉ deploy khi push main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3. Cài dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build project
      - name: Build project
        run: npm run build

      # 5. Upload build artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 6. Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
